version: '3'

services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: rabbitDB
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  myrabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5671:5671"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"

  pageviewservice:
    image: exoget/pageviewservice
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mysqldb
      - myrabbitmq
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/rabbitDB'
      SPRING_PROFILES_ACTIVE: 'mysql'
      SPRING_RABBITMQ_HOST: myrabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3